### PR TITLE
Fix for Sass::Rails 3.x

### PR DESCRIPTION
**Pull request by merqlove**
#210

### CODE REVIEW

**Comment by merqlove** [comment]
For now seems that it stable. Tests passed.

**Comment by jcemer** [comment]
Maybe a generic solution is better. What to think about a check like this:

~~~
if defined?(super)
  super_method.arity == 1 ? ? super(source) : super
else
  view_proxy.javascript_path(source, options)
end
~~~

**Comment by merqlove** [comment]
I think this is better. I will fix current pr.

Best regards, 
Alexander Merkulov

**Comment by merqlove** [comment]
We can't do this, `super_method` in Ruby from 2.2+.

**Comment by jcemer** [comment]
Sorry, you are right. 
Looking to the code I don't see a case that the `options` are used.
I think we could remove this params.

~~~
def javascript_path(source)
     if defined?(super)
       super
     else
       view_proxy.javascript_path(source, options)
     end
end
~~~

**Comment by merqlove** [comment]
I don't think so. Because this is what we use as helper. 
We cannot just delete it, this is View API of rjs-rails. :)

**Comment by merqlove** [comment]
This PR was did 5 month ago. 
Problem still actual.
So?

**Comment by carsomyr** [comment]
@merqlove Sorry for letting this fall through the cracks. I'll issue a minor release tonight.

**Comment by merqlove** [comment]
@carsomyr Ok. 
Anyway Rails 3 not working with Sprockets 3, as someone mentioned in #247

**Comment by carsomyr** [comment]
@merqlove How does 78d43f2 look?

**Comment by merqlove** [comment]
@carsomyr Thanks, looks good!

**Pull request closed without merging**
